### ISSUE TITLE
MediaStyle is deprecated since 26 API

### ISSUE THREAD

**Issue by fmaxx** [SergeyVinyar/AndroidAudioExample#2]
The solution is using - "android.support.v4.media.app.NotificationCompat.MediaStyle"

**Comment by SergeyVinyar** [comment]
Switched to SDK 26, commits 263381b85d05e8fa65b4281887931260fbac4ef7 and 263381b85d05e8fa65b4281887931260fbac4ef7.
And also I added an update block to the article.
Thank you.
