### ISSUE TITLE
Infinity loop in MediaControllerCompat.Callback()

### ISSUE THREAD

**Issue by fmaxx** [SergeyVinyar/AndroidAudioExample#3]
Could you add above?
`audioManager.abandonAudioFocus(audioFocusChangeListener)`

There is no problem in your case with ExoPlayer, but I'm getting the infinity events loop after : Play click -> Pause click -> Play click.

https://github.com/SergeyVinyar/AndroidAudioExample/blob/263381b85d05e8fa65b4281887931260fbac4ef7/app/src/main/java/ru/vinyarsky/androidaudioexample/service/PlayerService.java#L162

**Comment by SergeyVinyar** [comment]
Yeah, you're right. Anyway it's not a good idea to re-request a focus without abandoning it.
Please have a look at 840dd7b6030d706a4f74c2c14b7ca89f9a3e5bba. I think this might be a solution.
